### PR TITLE
Update do Dagger 2.12 (final) and Android M

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by danielpassos** [comment]
5 months without any comment I'm going to close it

**Comment by mewa** [comment]
Hey @danielpassos, sorry for the lack of communication. I had been really busy back then and later on it slipped off my mind somehow. 

If you still have that branch stashed somewhere, I'll be happy to review it in the following days and update everything in order.

Again, sorry for the poor experience and I hope that you don't hold a grudge :)

**Comment by danielpassos** [comment]
@mewa Np, you don't need to rush to review but a little comment is always welcome to people know you really care about the PR ;)

I have restored the brach and going to review it since it has 5 months, maybe I can improve it a little more.

**Review by mewa — APPROVED** [review]
Looks good :+1:

**Comment by mewa** [comment]
Thanks @danielpassos. I have also updated the article for which this example was created in the first place and gave you some credit :wink:

**Comment by danielpassos** [comment]
Yay, Thanks!

**Pull request merged**
